config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles
  resource :email, only: :create
  resources :chats, only: :index
  root to: 'chats#index'
  resources :payments, only: [:index, :create]
  namespace :pay do
    resources :events
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :article
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/email_processor.rb
class EmailProcessor
  def self.process(email)
  	user = User.find_by(email: email)
  	user.comments.create!(from: email.from, subject: email.subject, body: email.body)
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  include Stripe::Callbacks

  after_customer_subscription_created! do |customer, event|
    puts customer
  end

  attr_accessor :stripe_card_token

  def save_with_payment
    Stripe::Customer.create(description: email, plan: 'silver', card: stripe_card_token)
    save
    rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while creating customer: #{e.message}"
      errors.add :base, "There was a problem with your credit card."
      false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 

  has_many :comments

  def admin?
  	email == 'dilpreet.makkar92@gmail.com'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    puts 'hey'.duplicable?
    render plain: 'hey'
  end

  def new
  end

  def create
    render plain: 'got it'
  end

end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController

  def initialize_session
    puts "CHAT Session Initialized\n"
  end
  
  def system_msg(ev, msg)
    broadcast_message ev, { 
      user_name: 'system', 
      received: Time.now.to_s(:short), 
      msg_body: msg
    }
  end
  
  def user_msg(ev, msg)
    broadcast_message ev, { 
      user_name:  connection_store[:user], 
      received:   Time.now.to_s(:short), 
      msg_body:   ERB::Util.html_escape(msg) 
      }
  end
  
  def client_connected
    system_msg :new_message, "client #{client_id} connected"
  end
  
  def new_message
    user_msg :new_message, message[:message_body].dup
  end
  
  def new_user
    connection_store[:user] = message[:user_name]
    broadcast_user_list
  end
  
  def delete_user
    connection_store[:user] = nil
    system_msg "client #{client_id} disconnected"
    broadcast_user_list
  end
  
  def broadcast_user_list
    users = connection_store.collect_all(:user)
    broadcast_message :user_list, users
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
  end

end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

	def create
		UserMailer.receive(request.request_parameters)
	end
end

app/controllers/pay/events_controller.rb
class Pay::EventsController < ApplicationController

  def create
    puts "#{ request.body }"
    render json: { message: 'got the webhook' }
  end

  def index
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.save_with_payment
  end

  private

    def subscription_params
      params.require(:subscription).permit(:email, :stripe_card_token)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<% @articles.each do |article| %>
 <div>
   Name: <%= article.name %>
   Active: <%= article.active %>
 </div>
<% end %>   

app/views/articles/new.html.erb
<input id='article' type="button" />

app/views/chats/index.html.erb
<div id="chat" class="well" 
      data-uri="<%= request.host %>:<%= request.port %>/websocket">
</div>

<div class="form-inline well">
  <fieldset>
    <input type="text" class="input-medium" id="user_name">
    <input type="text" class="input-xlarge" id="message">
    <button id="send" class="btn btn-primary">Send</button>
  </fieldset>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

  </head>
  <body>
    <div class='username'>
    </div>
   <%= yield %>
  </body>
</html>

app/views/payments/create.html.erb
<h3>Payment Sucessfully created</h3>

app/views/payments/index.html.erb
<%= stripe_javascript_tag %>
<%= javascript_include_tag 'payment.js' %>
<div>
Subscribe for Rs.10.00
</div>
<%= form_for(@subscription, url: payments_path) do |f| %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <%= f.hidden_field :stripe_card_token %>
  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div><br>
  <div class="field">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div><br>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, { add_month_numbers: true }, { name: nil, id: "card_month" } %>
    <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, { name: nil, id: "card_year" } %>
  </div><br>
  <div id="stripe_error">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  <div class="field">
    <%= f.submit 'Pay', class: 'pay' %>
  </div>    
<% end %>